from .animals import Animal
from .alligator import Alligator
from .cow import Cow
from .deer import Deer
from .fish import Fish
from .fox import Fox
from .giraffe import Giraffe
from .hellbender import Hellbender
from .horse import Horse
from .salamander import Salamander
from .shark import Shark
from .slug import Slug
from .snake import Snake
from .turtle import Turtle
from .whale import Whale
from .worm import Worm
